-- Connexion en tant que SYSDBA puis création utilisateur
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER eshop IDENTIFIED BY Eshop123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, DBA TO eshop;
GRANT CREATE DATABASE LINK TO eshop;
GRANT CREATE PUBLIC DATABASE LINK TO eshop;
COMMIT;