ALTER SESSION SET CONTAINER = XEPDB1;

CREATE DATABASE LINK link_site1
  CONNECT TO eshop1 IDENTIFIED BY Eshop123
  USING 'SITE1';

CREATE DATABASE LINK link_site2
  CONNECT TO eshop2 IDENTIFIED BY Eshop123
  USING 'SITE2';

COMMIT;